"""
Meal improvement and recipe suggestion routes.

NOTE: Routes marked as premium-only — paywall check to be added when Stripe
is integrated.

Endpoints
---------
GET  /api/meals/suggestions?scan_id={id}
    Fetch improvement tips and curated/AI recipe suggestions for a past scan.

GET  /api/meals/recipes?cuisine={cuisine}&limit=10
    Browse the curated recipe library, optionally filtered by cuisine.

GET  /api/meals/recipes/{id}
    Full recipe detail including ingredient list.

POST /api/meals/shopping-list
    Create a shopping list from a recipe (optionally linked to a scan).

PUT  /api/meals/shopping-list/{id}
    Update which ingredients the user already has at home.

GET  /api/meals/shopping-list/{id}/comparison?scan_id={id}
    Side-by-side macro comparison of a recipe vs. a past food scan.
"""

from typing import Optional

from fastapi import APIRouter, Depends, HTTPException, Query

from models.schemas import (
    MealComparisonResponse,
    MealSideResponse,
    MealSuggestionsResponse,
    RecipeDetailResponse,
    RecipeResponse,
    ShoppingListCreateRequest,
    ShoppingListResponse,
    ShoppingListUpdateRequest,
)
from services.auth import require_premium as get_current_user  # All meals routes are PREMIUM-ONLY
from services.meal_suggestions import (
    generate_comparison,
    generate_improvement_tips,
    suggest_recipes,
)
from database.supabase import (
    create_shopping_list,
    get_curated_recipes_for_suggestions,
    get_food_scan_by_id,
    get_recipe_with_ingredients,
    get_recipes,
    get_shopping_list,
    update_shopping_list_items,
)

router = APIRouter()


# ---------------------------------------------------------------------------
# Suggestions
# ---------------------------------------------------------------------------

@router.get("/meals/suggestions", response_model=MealSuggestionsResponse)
async def meal_suggestions(
    scan_id: str = Query(..., description="ID of a previous food scan"),
    user_id: str = Depends(get_current_user),
):
    """
    Return improvement tips and healthier recipe alternatives for a past scan.

    The scan must belong to the authenticated user.  Tips are generated by
    Gemini; recipes come from the curated library first, with Gemini filling
    in the gaps when fewer than 3 curated matches beat the scan score.
    """
    scan = await get_food_scan_by_id(user_id, scan_id)
    if not scan:
        raise HTTPException(status_code=404, detail="Food scan not found.")

    # Fetch curated recipes (cuisine-filtered when possible)
    available = await get_curated_recipes_for_suggestions(scan.get("food_name", ""))

    tips, recipes = await _gather_suggestions(scan, available)

    return MealSuggestionsResponse(
        improvement_tips=tips,
        suggested_recipes=[RecipeResponse(**_to_recipe_response(r)) for r in recipes],
    )


async def _gather_suggestions(scan: dict, available: list[dict]):
    """Run tips and recipe generation concurrently."""
    import asyncio
    tips_coro    = generate_improvement_tips(scan)
    recipes_coro = suggest_recipes(scan, available, n=5)
    tips, recipes = await asyncio.gather(tips_coro, recipes_coro)
    return tips, recipes


# ---------------------------------------------------------------------------
# Recipe browsing
# ---------------------------------------------------------------------------

@router.get("/meals/recipes", response_model=list[RecipeResponse])
async def browse_recipes(
    cuisine: Optional[str] = Query(default=None, description="Filter by cuisine"),
    limit: int = Query(default=10, ge=1, le=50),
    user_id: str = Depends(get_current_user),
):
    """
    Browse the curated recipe library.

    Optionally filter by cuisine (indian, arab, japanese, italian, mexican,
    chinese, british, korean).  Returns at most `limit` recipes.
    """
    rows = await get_recipes(cuisine=cuisine, limit=limit)
    return [RecipeResponse(**_to_recipe_response(r)) for r in rows]


@router.get("/meals/recipes/{recipe_id}", response_model=RecipeDetailResponse)
async def get_recipe(
    recipe_id: str,
    user_id: str = Depends(get_current_user),
):
    """Return full recipe detail including the ingredient list."""
    row = await get_recipe_with_ingredients(recipe_id)
    if not row:
        raise HTTPException(status_code=404, detail="Recipe not found.")

    ingredients = row.pop("ingredients", []) or []
    return RecipeDetailResponse(
        **_to_recipe_response(row),
        ingredients=ingredients,
    )


# ---------------------------------------------------------------------------
# Shopping lists
# ---------------------------------------------------------------------------

@router.post("/meals/shopping-list", response_model=ShoppingListResponse)
async def create_shopping_list_route(
    body: ShoppingListCreateRequest,
    user_id: str = Depends(get_current_user),
):
    """
    Create a shopping list from a recipe.

    Provide `already_have` (list of ingredient names) to pre-mark items the
    user already owns.  Optionally link to a `scan_id` for later comparison.
    """
    # Verify recipe exists
    recipe = await get_recipe_with_ingredients(body.recipe_id)
    if not recipe:
        raise HTTPException(status_code=404, detail="Recipe not found.")

    # Verify scan ownership (if provided)
    if body.scan_id:
        scan = await get_food_scan_by_id(user_id, body.scan_id)
        if not scan:
            raise HTTPException(
                status_code=404,
                detail="Food scan not found or does not belong to you.",
            )

    shopping_list = await create_shopping_list(
        user_id=user_id,
        recipe_id=body.recipe_id,
        scan_id=body.scan_id,
        already_have=body.already_have,
        ingredients=recipe.get("ingredients", []),
    )
    return ShoppingListResponse(**shopping_list)


@router.put("/meals/shopping-list/{list_id}", response_model=ShoppingListResponse)
async def update_shopping_list_route(
    list_id: str,
    body: ShoppingListUpdateRequest,
    user_id: str = Depends(get_current_user),
):
    """
    Update which ingredients the user already has at home.

    Accepts a list of `{ingredient_name, already_have}` objects.  Only items
    belonging to a shopping list owned by the authenticated user are updated.
    """
    existing = await get_shopping_list(user_id, list_id)
    if not existing:
        raise HTTPException(
            status_code=404,
            detail="Shopping list not found or does not belong to you.",
        )

    updates = {item.ingredient_name: item.already_have for item in body.items}
    updated = await update_shopping_list_items(list_id, updates)
    return ShoppingListResponse(**updated)


# ---------------------------------------------------------------------------
# Comparison
# ---------------------------------------------------------------------------

@router.get(
    "/meals/shopping-list/{list_id}/comparison",
    response_model=MealComparisonResponse,
)
async def meal_comparison(
    list_id: str,
    scan_id: str = Query(..., description="ID of the original food scan to compare against"),
    user_id: str = Depends(get_current_user),
):
    """
    Side-by-side macro comparison between a recipe and a past food scan.

    Returns both macro profiles plus a list of human-readable improvement
    strings (e.g. "2× the protein", "40% less fat").
    """
    # Fetch shopping list (ownership check)
    shopping_list = await get_shopping_list(user_id, list_id)
    if not shopping_list:
        raise HTTPException(
            status_code=404,
            detail="Shopping list not found or does not belong to you.",
        )

    # Fetch recipe
    recipe_id = shopping_list.get("recipe_id")
    recipe = await get_recipe_with_ingredients(recipe_id)
    if not recipe:
        raise HTTPException(status_code=404, detail="Recipe not found.")

    # Fetch original scan (ownership check)
    scan = await get_food_scan_by_id(user_id, scan_id)
    if not scan:
        raise HTTPException(status_code=404, detail="Food scan not found.")

    improvements = generate_comparison(scan, recipe)

    return MealComparisonResponse(
        original_meal=MealSideResponse(
            name=scan.get("food_name", "Original meal"),
            calories=scan.get("calories"),
            protein_g=scan.get("protein_g"),
            carbs_g=scan.get("carbs_g"),
            fat_g=scan.get("fat_g"),
            fiber_g=scan.get("fiber_g"),
        ),
        new_meal=MealSideResponse(
            name=recipe.get("name", "Recipe"),
            calories=recipe.get("calories"),
            protein_g=recipe.get("protein_g"),
            carbs_g=recipe.get("carbs_g"),
            fat_g=recipe.get("fat_g"),
            fiber_g=recipe.get("fiber_g"),
        ),
        improvements=improvements,
    )


# ---------------------------------------------------------------------------
# Internal helpers
# ---------------------------------------------------------------------------

def _to_recipe_response(r: dict) -> dict:
    """
    Normalise a recipe row from Supabase into the RecipeResponse field set.

    Gemini-generated recipes may be missing ``id`` and ``is_curated``; supply
    safe defaults so the Pydantic model never raises a validation error.
    """
    return {
        "id":                r.get("id", ""),
        "name":              r.get("name", ""),
        "cuisine":           r.get("cuisine", ""),
        "description":       r.get("description"),
        "calories":          r.get("calories"),
        "protein_g":         r.get("protein_g"),
        "carbs_g":           r.get("carbs_g"),
        "fat_g":             r.get("fat_g"),
        "fiber_g":           r.get("fiber_g"),
        "prep_time_minutes": r.get("prep_time_minutes"),
        "servings":          r.get("servings", 1),
        "image_url":         r.get("image_url"),
        "is_curated":        r.get("is_curated", False),
    }
